app_user: roboshop
url: "https://stan-robotshop.s3.amazonaws.com/shipping-v3.zip"
schema_type: mysql
setup_schema: true 
schema: 
  - app-user
  - schema 
  - master-data
secrets: "{{ lookup('community.hashi_vault.hashi_vault', 'secret=roboshop-dev/data/mysql token={{vault_token}} url=https://vault.roboshop.internal:8200 validate_certs=False') }}"