- name: Copying the repo
  ansible.builtin.copy:
    src: mongo.repo 
    dest: /etc/yum.repos.d/mongo.repo

- name: Install {{component}}
  ansible.builtin.dnf:
    name: mongodb-org 
    state: latest

- name: Replacing loopback ip
  ansible.builtin.replace:
    path: /etc/mongod.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: Restarting {{component}}
  ansible.builtin.systemd_service:
    name: mongod  
    state: started
    enabled: true
    daemon_reload: true

- name: Configuring hostname
  ansible.builtin.include_role:      # Through this we can all a specific task from a role
    name: common                     # Name of the role to be called 
    tasks_from: set-hostname         # Name of the task in the above mentioned role 
