- name: Enabling 1.24 of nginx
  ansible.builtin.shell: dnf module disable nginx -y ; dnf module enable nginx:1.24 -y

- name: Install nginx
  ansible.builtin.dnf:
    name: nginx
    state: latest 

- name: Cleanup of old content 
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: absent 

- name: Creating UI Directoru
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: directory  

- name: Download and extract 
  ansible.builtin.unarchive:
    src: "{{ url }}"
    dest: /usr/share/nginx/html
    remote_src: yes

- name: Copying proxy file 
  ansible.builtin.template:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf  

- name: Restarting {{component}}
  ansible.builtin.systemd_service:
    name: nginx 
    state: restarted
    enabled: true
    daemon_reload: true

- name: Configuring hostname
  ansible.builtin.include_role:      # Through this we can all a specific task from a role
    name: common                     # Name of the role to be called 
    tasks_from: set-hostname  # Name of the task in the above mentioned role 



