- name: Install {{ component }}
  ansible.builtin.dnf:
    name: mysql-server
    state: latest

- name: Installing hvac
  ansible.builtin.include_role:       
    name: common                      
    tasks_from: vault-prereq

- name: Starting {{ component }}
  ansible.builtin.systemd_service:
    name: mysqld  
    state: started
    enabled: true

- name: Configuring {{ component }} root password 
  ansible.builtin.shell: mysql_secure_installation --set-root-pass {{secrets.root_password}} || true 

- name: Configuring hostname
  ansible.builtin.include_role:      
    name: common                    
    tasks_from: set-hostname