- name: Install {{ component }}
  ansible.builtin.dnf:
    name: mysql-server
    state: latest

- name: Starting {{ component }}
  ansible.builtin.systemd_service:
    name: mysqld  
    state: started
    enabled: true

- name: Configuring {{ component }} root password 
  ansible.builtin.shell:  mysql_secure_installation --set-root-pass RoboShop@1