- name: Enabling Nodejs20 Repo
  ansible.builtin.shell: dnf module disable nodejs -y ; dnf module enable nodejs:20 -y

- name: Install nodejs
  ansible.builtin.dnf:
    name: nodejs
    state: latest

- name: Cleanup of old app 
  ansible.builtin.file:
    path: /app
    state: absent 
    ignore_errors: yes    

- name: Creating App Directory
  ansible.builtin.file:
    path: /app
    state: directory  

- name: Creating App User
  ansible.builtin.user:
    name: "{{app_user}}"
    comment: Application User 

- name: Download and extract {{component}} app 
  ansible.builtin.unarchive:
    src: "{{ url }}"
    dest: /app 
    remote_src: yes

- name: Generating node_modules
  community.general.npm:
    path: /app 

- name: Configuring {{component}} Systemd
  ansible.builtin.template:
    src: catalogue.service
    dest: /etc/systemd/system/catalogue.service

- name: Restarting {{component}}
  ansible.builtin.systemd_service:
    name: "{{component}}"
    state: restarted
    enabled: true
    daemon_reload: true

- name: Configuring hostname
  ansible.builtin.include_role:      # Through this we can all a specific task from a role
    name: common                     # Name of the role to be called 
    tasks_from: set-hostname  # Name of the task in the above mentioned role 



