- name: Install mysql shell  
  ansible.builtin.dnf:
    name: mysql 
    state: latest

- name: Injecting the mysql schema
  loop: "{{ schema }}"
  ansible.builtin.shell: mysql -h mysql-{{env}}.cloudapps.today  -uroot -p{{secrets.root_password}} < /app/db/{{ item }}.sql
  