- name: Install MongoShell 
  ansible.builtin.dnf:
    name: mysql 
    state: latest

- name: Injecting the mysql schema
  loop: "{{ schema }}"
  ansible.builtin.shell: mysql -h mysql-{{env}}.roboshop.internal  -uroot -p{{secrets.root_password}} < /app/db/{{ item }}.sql
  