- name: Cleanup of old app 
  ansible.builtin.file:
    path: /app
    state: absent 
  ignore_errors: true   

- name: Creating App Directory
  ansible.builtin.file:
    path: /app
    state: directory  

- name: Creating App User
  ansible.builtin.user:
    name: "{{ app_user }}"
    comment: Application User 

- name: Download and extract {{ component }} app 
  ansible.builtin.unarchive:
    src: "{{ url }}"
    dest: /app 
    remote_src: yes